tags:
  [
    {
      frame: "tag_1",
      id: 1,
      corners: [
        [-0.0805,0.0805,0.0],
        [0.0805,0.0805,0.0],
        [0.0805,-0.0805,0.0]
      ]
    },
    {
      frame: "tag_2",
      id: 2,
      corners: [
        [-0.0805,0.0805,0.0],
        [0.0805,0.0805,0.0],
        [0.0805,-0.0805,0.0]
      ]
    },
    {
      frame: "tag_3",
      id: 3,
      corners: [
        [-0.0805,0.0805,0.0],
        [0.0805,0.0805,0.0],
        [0.0805,-0.0805,0.0]
      ]
    },
    {
      frame: "tag_4",
      id: 4,
      corners: [
        [-0.0805,0.0805,0.0],
        [0.0805,0.0805,0.0],
        [0.0805,-0.0805,0.0]
      ]
    }
  ]
bundles:
  [
  ]

# Marker corner order:
# 1          2
#  HD########
#  #ID#  ####
#  ##  ##  ##
#  ####  ####
#  ##########
# 4          3
