tags:
  [
    {
      frame: "tag_5",
      id: 5,
      corners: [
        [-0.0805,0.0805,0.0],
        [0.0805,0.0805,0.0],
        [0.0805,-0.0805,0.0]
      ]
    },
    {
      frame: "tag_6",
      id: 6,
      corners: [
        [-0.0805,0.0805,0.0],
        [0.0805,0.0805,0.0],
        [0.0805,-0.0805,0.0]
      ]
    },
    {
      frame: "tag_7",
      id: 7,
      corners: [
        [-0.0805,0.0805,0.0],
        [0.0805,0.0805,0.0],
        [0.0805,-0.0805,0.0]
      ]
    },
    {
      frame: "tag_8",
      id: 8,
      corners: [
        [-0.0805,0.0805,0.0],
        [0.0805,0.0805,0.0],
        [0.0805,-0.0805,0.0]
      ]
    }
  ]
bundles:
  [
  ]

# Marker corner order:
# 1          2
#  HD########
#  #ID#  ####
#  ##  ##  ##
#  ####  ####
#  ##########
# 4          3
